apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-credentials"
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | quote }}
