apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  annotations:
    app.kubernetes.io/name: {{ .Values.name }}
data:
  redis.conf: |
    appendonly {{ .Values.redisConfig.appendonly }}
