apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  annotations:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["redis-server"]
          args:
            - "/usr/local/etc/redis/redis.conf"
            {{- if .Values.auth.enabled }}
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            {{- end }}
          ports:
            - containerPort: 6379
          {{- if .Values.auth.enabled }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-auth
                  key: redis-password
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/redis
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}-config
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-data
        {{- end }}
