{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-auth
  annotations:
    app.kubernetes.io/name: {{ .Values.name }}
type: Opaque
stringData:
  redis-password: {{ .Values.auth.password | quote }}
{{- end }}
