services:
  postgres-db:
    container_name: kdcube-postgres
    image: pgvector/pgvector:pg16
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: kdcube-redis
    image: redis:latest
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    env_file:
      - .env
    environment:
      # Keycloak configuration
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    restart: unless-stopped
    command: start-dev

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: /home/crackup/fun/postgres-data
      o: bind

  redis-data:
    driver: local
    driver_opts:
      type: none
      device: /home/crackup/fun/redis-data
      o: bind